#!/usr/bin/env python3
"""Resume the local Theos SDK pipeline from a completed GitHub header-shard run.

This intentionally does not import CI manifests into the normal local shard cache:
the manifests were produced by GitHub's Clang, so keeping them in a separate
provenance-labelled directory avoids pretending they were generated by the local
compiler. The downstream ABI/bridge/planner stages are still executed locally.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Sequence

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOLS_ROOT = REPO_ROOT / "tools" / "compat_surface"
sys.path.insert(0, str(TOOLS_ROOT))

import local_theos_preflight as local  # noqa: E402

EXPECTED_HEADER_COUNT = 5118
DEFAULT_RUN_ID = 33534466454
DEFAULT_RUN_NUMBER = 37
DEFAULT_RUN_HEAD = "ca4a2e71b997b55d0176acb21ebdda55fd928fbd"
MANIFEST_RE = re.compile(r"header-shard-(\d+)\.json$")


class CiResumeError(RuntimeError):
    pass


def discover_manifests(source: Path) -> list[Path]:
    found: dict[int, Path] = {}
    duplicates: list[int] = []
    for path in source.rglob("header-shard-*.json") if source.exists() else []:
        match = MANIFEST_RE.search(path.name)
        if not match:
            continue
        index = int(match.group(1))
        if index in found:
            duplicates.append(index)
        else:
            found[index] = path

    expected = set(range(local.HEADER_SHARD_COUNT))
    missing = sorted(expected - set(found))
    extra = sorted(set(found) - expected)
    if missing or extra or duplicates:
        raise CiResumeError(
            "CI shard set is not exact: "
            f"missing={missing} extra={extra} duplicates={sorted(set(duplicates))}"
        )

    manifests: list[Path] = []
    for index in range(local.HEADER_SHARD_COUNT):
        path = found[index]
        if not local.valid_cached_shard(path, index):
            raise CiResumeError(f"invalid CI shard manifest {index}: {path}")
        manifest = json.loads(path.read_text(encoding="utf-8"))
        coverage = manifest["coverage"]
        if coverage.get("sdk_header_count") != EXPECTED_HEADER_COUNT:
            raise CiResumeError(
                f"CI shard {index} reports sdk_header_count="
                f"{coverage.get('sdk_header_count')!r}, expected {EXPECTED_HEADER_COUNT}"
            )
        manifests.append(path.resolve())
    return manifests


def output_key(run_id: int) -> str:
    return f"ci-run-{run_id}-{local.pipeline_cache_key()}"


def run_downstream_from_ci(
    *,
    sdk_root: Path,
    workspace: Path,
    manifests: Sequence[Path],
    run_id: int,
    run_number: int,
    source_head: str,
    clang_timeout: int,
    wall_timeout: int,
    force: bool,
) -> Path:
    output = workspace / "output" / output_key(run_id)
    bundle = output / "bundle"
    log = output / "sdk-preflight.log"
    metadata = output / "ci-resume.json"

    if (
        not force
        and (bundle / "compatibility-plan.json").is_file()
        and (bundle / "header-signatures.json").is_file()
    ):
        print(f"[ci-resume] reusing completed downstream bundle: {bundle}")
        return bundle

    output.mkdir(parents=True, exist_ok=True)
    if bundle.exists():
        shutil.rmtree(bundle)

    command = [
        sys.executable,
        str(TOOLS_ROOT / "sdk_compatibility.py"),
        "--sdk-root",
        str(sdk_root),
        "--output-dir",
        str(bundle),
        "--compiler-batch-size",
        str(local.COMPILER_BATCH_SIZE),
        "--timeout",
        str(clang_timeout),
    ]
    for manifest in manifests:
        command += ["--header-manifest", str(manifest)]

    print(
        f"[ci-resume] GitHub Theos run #{run_number} ({run_id}) supplied "
        f"{len(manifests)}/{local.HEADER_SHARD_COUNT} verified header manifests"
    )
    print(f"[ci-resume] source head: {source_head}")
    print("[ci-resume] running merge + AAPCS64 + Win64 + bridge/planner stages locally")

    code, elapsed = local.timed_command(command, seconds=wall_timeout, log=log)
    metadata.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "github_run_id": run_id,
                "github_run_number": run_number,
                "github_source_head": source_head,
                "repo_head": local.repo_head(),
                "theos_sdk_commit": local.THEOS_SDK_COMMIT,
                "sdk": local.SDK_RELATIVE_PATH.as_posix(),
                "header_manifest_count": len(manifests),
                "sdk_header_count": EXPECTED_HEADER_COUNT,
                "local_clang": local.clang_identity(),
                "pipeline_cache_key": local.pipeline_cache_key(),
                "exit_code": code,
                "elapsed_seconds": round(elapsed, 3),
                "log": str(log),
                "bundle": str(bundle),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    if code != 0:
        detail = local.tail(log, 180)
        raise CiResumeError(
            f"local downstream preflight failed with exit code {code}"
            + (f"\n--- diagnostic tail ---\n{detail}" if detail else "")
        )

    print(f"[ci-resume] downstream pipeline OK ({elapsed:.1f}s)")
    print(f"[ci-resume] bundle: {bundle}")
    return bundle


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument(
        "--source",
        type=Path,
        default=REPO_ROOT / "out" / "local-theos-preflight" / f"ci-run-{DEFAULT_RUN_ID}",
        help="directory containing downloaded theos-sdk-header-shard-* artifacts",
    )
    result.add_argument(
        "--workspace",
        type=Path,
        default=REPO_ROOT / "out" / "local-theos-preflight",
    )
    result.add_argument("--run-id", type=int, default=DEFAULT_RUN_ID)
    result.add_argument("--run-number", type=int, default=DEFAULT_RUN_NUMBER)
    result.add_argument("--source-head", default=DEFAULT_RUN_HEAD)
    result.add_argument("--skip-tests", action="store_true")
    result.add_argument("--force", action="store_true")
    result.add_argument("--clang-timeout", type=int, default=local.CLANG_TIMEOUT_SECONDS)
    result.add_argument("--full-wall-timeout", type=int, default=local.FULL_PREFLIGHT_WALL_TIMEOUT_SECONDS)
    return result


def main(argv: Sequence[str] | None = None) -> int:
    args = parser().parse_args(argv)
    workspace = args.workspace.resolve()
    source = args.source.resolve()
    try:
        local.ensure_tools()
        sdk_root = local.ensure_sdk(workspace)
        if not args.skip_tests:
            local.run_tests()
        manifests = discover_manifests(source)
        run_downstream_from_ci(
            sdk_root=sdk_root,
            workspace=workspace,
            manifests=manifests,
            run_id=args.run_id,
            run_number=args.run_number,
            source_head=args.source_head,
            clang_timeout=args.clang_timeout,
            wall_timeout=args.full_wall_timeout,
            force=args.force,
        )
        return 0
    except (CiResumeError, local.LocalPreflightError, OSError, subprocess.CalledProcessError) as exc:
        print(f"[ci-resume] ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
